version: "3.7"

services:
  wallet-web-client:
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/ebsi/wallet-web-client:development_ebsiint-2439-release202011_v1.0.0
    build:
      context: ../..
      args:
        REACT_APP_EBSI_ENV: ${REACT_APP_EBSI_ENV:?REACT_APP_EBSI_ENV is not defined or empty}
        REACT_APP_WALLET: ${REACT_APP_WALLET:?REACT_APP_WALLET is not defined or empty}
