version: "3.7"

services:
  wallet-web-client:
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/intebsi/wallet-web-client:integration_ebsiint-2080-ci_v0.0.1
    build:
      context: ../..
      args:
        REACT_APP_EBSI_ENV: ${REACT_APP_EBSI_ENV:?REACT_APP_EBSI_ENV is not defined or empty}
        REACT_APP_WALLET: ${REACT_APP_WALLET:?REACT_APP_WALLET is not defined or empty}
